name: Build Flutter APK and EXE

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-android:
    name: Build Android APK
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: internet_speed_meter 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      # بناء ملف APK واحد بحجم صغير مخصص للهواتف الحديثة
      - name: Build Single Small APK (ARM64)
        run: flutter build apk --release --target-platform android-arm64

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Android-APK-Small
          path: internet_speed_meter/build/app/outputs/flutter-apk/app-release.apk

  build-windows:
    name: Build Windows EXE
    runs-on: windows-latest
    defaults:
      run:
        working-directory: internet_speed_meter

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get
        
      # هذه الخطوة تقوم بحل خطأ الويندوز برمجياً وتلقائياً قبل البناء
      - name: Patch CMakeLists to Fix C++ Error
        run: |
          $file = "windows\CMakeLists.txt"
          $content = Get-Content $file -Raw
          $content = $content -replace "project\((.*?)\)", "project(`$1)`n`nadd_compile_definitions(_SILENCE_EXPERIMENTAL_COROUTINE_DEPRECATION_WARNINGS)"
          Set-Content -Path $file -Value $content

      - name: Build Windows
        run: flutter build windows --release

      - name: Upload Windows EXE
        uses: actions/upload-artifact@v4
        with:
          name: Windows-Release-Files
          path: internet_speed_meter/build/windows/x64/runner/Release/
